# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c

script:
- xcodebuild clean build -workspace Transloadit.xcworkspace -scheme Transloadit-Example -destination 'platform=iOS Simulator,name=iPhone 7 Plus,OS=latest'
